# Generated by Django 2.0b1 on 2017-10-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preservedrecipe', '0002_recipestep_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientmaster',
            name='text',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='text',
            field=models.TextField(default='', max_length=200),
        ),
    ]
