# Generated by Django 2.0b1 on 2017-10-28 01:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preservedrecipe', '0003_auto_20171028_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_text', models.CharField(max_length=200)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('classificatio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preservedrecipe.Classification')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='classificati',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='preservedrecipe.Classification'),
            preserve_default=False,
        ),
    ]
