# Generated by Django 2.0b1 on 2017-10-28 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preservedrecipe', '0004_auto_20171028_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmaster',
            name='classificati',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='preservedrecipe.Classification'),
            preserve_default=False,
        ),
    ]
