# Generated by Django 2.0b1 on 2017-10-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preservedrecipe', '0005_ingredientmaster_classificati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='classificatio',
        ),
        migrations.RemoveField(
            model_name='ingredientmaster',
            name='classificati',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='classificati',
        ),
        migrations.AddField(
            model_name='classification',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_class', to='preservedrecipe.Classification'),
        ),
        migrations.AddField(
            model_name='ingredientmaster',
            name='classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Ingredient_class', to='preservedrecipe.Classification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Recipe_class', to='preservedrecipe.Classification'),
            preserve_default=False,
        ),
    ]
