# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 21:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 21, 54, 34, 233208, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
